export const Font = {
  ThinItalic: 'JetBrainsMonoNL-ThinItalic',
  Thin: 'JetBrainsMonoNL-Thin',
  SemiBoldItalic: 'JetBrainsMonoNL-SemiBoldItalic',
  SemiBold: 'JetBrainsMonoNL-SemiBold',
  Regular: 'JetBrainsMonoNL-Regular',
  Italic: 'JetBrainsMonoNL-Italic',
  MediumItalic: 'JetBrainsMonoNL-MediumItalic',
  LightItalic: 'JetBrainsMonoNL-LightItalic',
  Medium: 'JetBrainsMonoNL-Medium',
  Light: 'JetBrainsMonoNL-Light',
  ExtraLightItalic: 'JetBrainsMonoNL-ExtraLightItalic',
  ExtraLight: 'JetBrainsMonoNL-ExtraLight',
  ExtraBoldItalic: 'JetBrainsMonoNL-ExtraBoldItalic',
  ExtraBold: 'JetBrainsMonoNL-ExtraBold',
  BoldItalic: 'JetBrainsMonoNL-BoldItalic',
  Bold: 'JetBrainsMonoNL-Bold',
};

export const FontFamily = {
  ThinItalic: {fontFamily: Font.ThinItalic},
  Thin: {fontFamily: Font.Thin},
  SemiBoldItalic: {fontFamily: Font.SemiBoldItalic},
  SemiBold: {fontFamily: Font.SemiBold},
  Regular: {fontFamily: Font.Regular},
  Italic: {fontFamily: Font.Italic},
  MediumItalic: {fontFamily: Font.MediumItalic},
  LightItalic: {fontFamily: Font.LightItalic},
  Medium: {fontFamily: Font.Medium},
  Light: {fontFamily: Font.Light},
  ExtraLightItalic: {fontFamily: Font.ExtraLightItalic},
  ExtraLight: {fontFamily: Font.ExtraLight},
  ExtraBoldItalic: {fontFamily: Font.ExtraBoldItalic},
  ExtraBold: {fontFamily: Font.ExtraBold},
  BoldItalic: {fontFamily: Font.BoldItalic},
  Bold: {fontFamily: Font.Bold},
};
